AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  BearOfTheDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bear_of_the_day.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: Sends an email with a bear picture of the day.
      MemorySize: 128
      Timeout: 10
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: 'bear-of-the-day'
      Events:
        BearOfTheDay:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)