AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Bear of the Day, to send bears to people who want bears in their inbox.
Resources:
  BearOfTheDayFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bear_of_the_day.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: Sends an email with a bear picture of the day.
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          OPENAI_API_KEY: !Sub ${OpenAIKey}
          RECIPIENTS: !Sub ${Recipients}
          SENDER_EMAIL: !Sub ${SenderEmail}
          SENDER_PASS: !Sub ${SenderPass}
          FILE_PATH: !Sub ${FilePath}
      Policies:
        - AWSLambdaBasicExecutionRole
        - S3ReadPolicy:
            BucketName: 'bear-of-the-day'
      Events:
        BearOfTheDay:
          Type: Schedule
          Properties:
            Schedule: cron(0 8 * * ? *)
  # BearOfTheDayBucket:
  #   Type: 'AWS::S3::Bucket'
  #   Properties:
  #     BucketName: bear-of-the-day
  #     AccessControl: PublicRead
  #     WebsiteConfiguration:
  #       IndexDocument: index.html

Parameters:
  OpenAIKey:
    Type: String
  Recipients:
    Type: String
  SenderEmail:
    Type: String
  SenderPass:
    Type: String
  FilePath:
    Type: String