name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 aws-sam-cli
    
    - name: Delete stack if in ROLLBACK_FAILED state
      run: |
        STATUS=$(aws cloudformation describe-stacks --stack-name BEAR-OF-THE-DAY --query 'Stacks[0].StackStatus' --output text)
        if [ "$STATUS" == "ROLLBACK_FAILED" ]; then
          aws cloudformation delete-stack --stack-name BEAR-OF-THE-DAY
          while [ "$STATUS" != "DELETE_COMPLETE" ]; do
            sleep 10
            STATUS=$(aws cloudformation describe-stacks --stack-name BEAR-OF-THE-DAY --query 'Stacks[0].StackStatus' --output text)
          done
        fi

    - name: Package Lambda function
      run: sam package --output-template-file packaged.yaml --s3-bucket bear-of-the-day

    - name: Deploy Lambda function
      run: sam deploy --template-file packaged.yaml --region us-east-2 --capabilities CAPABILITY_IAM --stack-name BEAR-OF-THE-DAY

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-2