name: Deploy Vue App to Amplify

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Install Amplify CLI 
      run: |
        npm install -g @aws-amplify/cli
   
    - name: Install dependencies
      run: npm install
      working-directory: ./frontend

    - name: Pull Amplify project
      run: |
        amplify pull --appId ${{ secrets.AMPLIFY_APP_ID }} --envName ${{ vars.AMPLIFY_ENV_NAME }}
      working-directory: ./frontend

    - name: Publish to Amplify
      run: |
        amplify publish --simple
      working-directory: ./frontend
